version: '3'
services: 
    flask-new:
        build: .
        volumes:
            - .:/usr/src/app
        ports: 
            - 80:80
        environment: 
            - FLASK_APP=app.py
            - FLASK_DEBUG=1
            - 'RUN=flask run --host=0.0.0.0 --port=80'
        command: flask run --host=0.0.0.0 --port=80
            