FROM tiangolo/uwsgi-nginx:python3.8
RUN echo "ipv6" >> /etc/modules
RUN mkdir /usr/src/app
COPY . /usr/src/app
WORKDIR /usr/src/app
EXPOSE 80
RUN pip install -r /usr/src/app/requirements.txt
CMD ["python", "app.py"]